version: '3.8'

services:
    mongo:
        image: mongo
        container_name: mongo
        environment:
            - MONGO_INITDB_DATABASE=gestor-pedido
            - MONGO_INITDB_ROOT_USERNAME=thimilo
            - MONGO_INITDB_ROOT_PASSWORD=123456
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mongo-express:
        image: mongo-express
        container_name: mexpress
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=thimilo
            - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
            - ME_CONFIG_BASICAUTH_USERNAME=thimilo
            - ME_CONFIG_BASICAUTH_PASSWORD=123456
        links:
            - mongo
        restart: unless-stopped
        ports:
          - "8083:8081"
